### ISSUE TITLE
self.ipv4_addresses is empty list of list of string

### ISSUE THREAD

**Issue by anibal-aguila** [Naman1997/simple-fcos-cluster#11]
hi, 

the ipv4_addresses list seems to be empty....
issue in the line 84 of modules/domain/main.tf line 84

```
│ Error: Error in function call
│
│   on modules/domain/main.tf line 84, in resource "proxmox_virtual_environment_vm" "node":
│   84:       ADDRESS = element([for addresses in self.ipv4_addresses : addresses[0] if addresses[0] != "127.0.0.1"], 0)
│     ├────────────────
│     │ while calling element(list, index)
│     │ self.ipv4_addresses is empty list of list of string
│
│ Call to function "element" failed: cannot use element function with an empty list.
```

Regards,

**Comment by Naman1997** [comment]
Hi! Apologies for the late response, I've moved recently for my higher studies and completely missed this.

It's a bit strange that this happens because this should pick the local ip as long as you're in the same network as the proxmox node. Can you share your tfstate file after running terraform apply?

Unfortunately I'm unable to reproduce this issue as of now as I do not have my proxmox server anymore. However, I'll be happy to review and merge code changes.

**Comment by Naman1997** [comment]
There is a different version using talos that I had switched to. Let me know if it works better for you.

https://github.com/Naman1997/simple-talos-cluster

**Comment by Naman1997** [comment]
I was finally able to spend some time today on this. I created a virtualized proxmox env to test this. The issue is that if the virtual machine takes too long to boot, then the qemu agent can timeout. Since the guest agent is responsible for letting proxmox know the ip address, this becomes a problem and we have the stacktrace @anibal-aguila mentioned above.

Thanks for reporting this!
